%functia principala
function figura(N,A,f,R,C,L,Ordin_R,Ordin_L,Ordin_C,Ordin_v,Ordin_f,Selectare_circuit,Permanent,Tranzitoriu,Plot)
%Realizarea figurii
%------------------------------------------------------------------------------
figure('Name','Comportarea in timp a circuitului RLC',...
       'Units','Normalized',...
       'Position',[0.1 0.1 0.8 0.8],...
       'NumberTitle','off');   
%------------------------------------------------------------------------------  
%Container pentru gruparea elementelor de interfata
%ce vor alcatui datele de intrare ale circuitului
%Elemente de interfata( uicontrol ) incluse: Text, Edit, PopupMenu
%------------------------------------------------------------------------------
RG1=uibuttongroup('Visible','on',...
                  'ForegroundColor','black',...
                  'Title','Date de intrare',...
                  'FontSize',11,...
                  'TitlePosition','centertop',...
                  'Tag','radiobutton',...
                  'HighlightColor',[0 1 0.6],...
                  'Position',[0.025 0.6 0.17 0.385]);
%------------------------------------------------------------------------------
%Elemente de interfata ce reprezinta si permit modificarea valorii
%rezistentei din circuit
%Prin PopupMenu si prin interpretarea valorii acestuia se modifica 
%ordinul de marime a rezistentei
%Valori permise pentru ordinul de marime [1 10^3 10^6 10^9]
%Valori corespunzatoare pentru PopupMenu [1 2 3 4]
%Prestabilit Ordin_R=1
%------------------------------------------------------------------------------
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.05 0.585 0.3 0.2],...
          'HorizontalAlignment','left',...
          'FontSize',10,...
          'String','R=',...
          'ForegroundColor',[0.8 0.4 0],...
          'Parent', RG1);       
uicontrol ('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.15 0.695 0.39 0.105],...
           'HorizontalAlignment','right',...
           'FontSize',10,...
           'String', num2str(R),...
           'ForegroundColor',[0.8 0.4 0],...
           'Parent', RG1,...
           'Callback','R=str2num(get(gco,''string''))');
uicontrol('Style','PopupMenu',...                
          'Units','normalized',...                
          'Position',[0.55 0.6 0.3 0.2],...
          'FontSize',10,...
          'String',strcat(char(hex2dec('03A9')),'|k',char(hex2dec('03A9')),'|M',char(hex2dec('03A9')),'|G',char(hex2dec('03A9'))),...
          'Value',Ordin_R,...
          'ForegroundColor',[0.8 0.4 0],...
          'Parent', RG1,...
          'Callback','Ordin_R=get(gco,''value'')');
switch Ordin_R
    case 2
        R=R*10^3;
    case 3
        R=R*10^6;
    case 4
        R=R*10^9;
end
%------------------------------------------------------------------------------
%Elemente de interfata ce reprezinta si permit modificarea valorii
%inductantei bobinei din circuit
%Prin PopupMenu si prin interpretarea valorii acestuia se modifica 
%ordinul de marime a inductantei din bobina
%Valori permise pentru ordinul de marime [10^(-12) 10^(-9) 10^(-6) 10^(-3) 1]
%Valori corespunzatoare pentru PopupMenu [1 2 3 4 5]
%Prestabilit Ordin_L=5
%------------------------------------------------------------------------------
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.05 0.435 0.3 0.2],...
          'HorizontalAlignment','left',...
          'FontSize',10,...
          'String','L=',...
          'ForegroundColor',[0.25 0.25 0.25],...
          'Parent', RG1);
uicontrol ('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.15 0.545 0.39 0.105],...
           'HorizontalAlignment','right',...
           'FontSize',10,...
           'String', num2str(L),...
           'ForegroundColor',[0.25 0.25 0.25],...
           'Parent', RG1,...
           'Callback','L=str2num(get(gco,''string''))');
uicontrol('Style','PopupMenu',...                
          'Units','normalized',...                
          'Position',[0.55 0.45 0.3 0.2],...
          'FontSize',10,...
          'String',strcat('pH|nH|',char(hex2dec('03BC')),'H|mH|H'),...
          'Value',Ordin_L,...
          'ForegroundColor',[0.25 0.25 0.25],...
          'Parent', RG1,...
          'Callback','Ordin_L=get(gco,''value'')');
switch Ordin_L
    case 1
        L=L*10^(-12);
    case 2
        L=L*10^(-9);
    case 3
        L=L*10^(-6);
    case 4
        L=L*10^(-3);
end
%------------------------------------------------------------------------------
%Elemente de interfata ce reprezinta si permit modificarea valorii
%capacitatii condensatorului din circuit
%Prin PopupMenu si prin interpretarea valorii acestuia se modifica 
%ordinul de marime a capacitatii condensatorului
%Valori permise pentru ordinul de marime [10^(-12) 10^(-9) 10^(-6) 10^(-3) 1]
%Valori corespunzatoare pentru PopupMenu [1 2 3 4 5]
%Prestabilit Ordin_C=5
%------------------------------------------------------------------------------
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.05 0.285 0.3 0.2],...
          'HorizontalAlignment','left',...
          'FontSize',10,...
          'String','C=',...
          'ForegroundColor',[0 0.6 0],...
          'Parent', RG1);
uicontrol ('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.15 0.395 0.39 0.105],...
           'HorizontalAlignment','right',...
           'FontSize',10,...
           'String', num2str(C),...
           'ForegroundColor',[0 0.6 0],...
           'Parent', RG1,...
           'Callback','C=str2num(get(gco,''string''))');
uicontrol('Style','PopupMenu',...                
          'Units','normalized',...                
          'Position',[0.55 0.3 0.3 0.2],...
          'FontSize',10,...
          'String',strcat('pF|nF|',char(hex2dec('03BC')),'F|mF|F'),...
          'Value',Ordin_C,...
          'ForegroundColor',[0 0.6 0],...
          'Parent', RG1,...
          'Callback','Ordin_C=get(gco,''value'')');
switch Ordin_C
    case 1
        C=C*10^(-12);
    case 2
        C=C*10^(-9);
    case 3
        C=C*10^(-6);
    case 4
        C=C*10^(-3);
end
%------------------------------------------------------------------------------
%Elemente de interfata ce reprezinta si permit modificarea valorii
%tensiunii din circuit
%Prin PopupMenu si prin interpretarea valorii acestuia se modifica 
%ordinul de marime a tensiunii aplicate
%Valori permise pentru ordinul de marime [10^(-3) 1 10^3 10^6 10^9]
%Valori corespunzatoare pentru PopupMenu [1 2 3 4 5]
%Prestabilit Ordin_v=2
%------------------------------------------------------------------------------
tensiune=uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.05 0.135 0.3 0.2],...
          'HorizontalAlignment','left',...
          'FontSize',10,...
          'String','v=',...
          'ForegroundColor',[1 0.2 0.2],...
          'Parent', RG1);
if Tranzitoriu==1
    set(tensiune,'String','V=');
end
uicontrol ('Style','Edit',...
           'Units','Normalized',...
           'Position',[0.15 0.245 0.39 0.105],...
           'HorizontalAlignment','right',...
           'FontSize',10,...
           'String', num2str(A),...
           'ForegroundColor',[1 0.2 0.2],...
           'Parent', RG1,...
           'Callback','A=str2num(get(gco,''string''))'); 
uicontrol('Style','PopupMenu',...                
          'Units','normalized',...                
          'Position',[0.55 0.15 0.3 0.2],...
          'FontSize',10,...
          'String','mV|V|kV|MV|GV',...
          'Value',Ordin_v,...
          'ForegroundColor',[1 0.2 0.2],...
          'Parent', RG1,...
          'Callback','Ordin_v=get(gco,''value'')');
switch Ordin_v
    case 1
        A=A*10^(-3);
    case 3
        A=A*10^3;
    case 4
        A=A*10^6;
    case 5
        A=A*10^9;
end
%------------------------------------------------------------------------------
%Elemente de interfata ce reprezinta si permit modificarea valorii
%frecventei semnalului aplicat
%Prin PopupMenu si prin interpretarea valorii acestuia se modifica 
%ordinul de marime a frecventei
%Valori permise pentru ordinul de marime [1 10^3 10^6 10^9]
%Valori corespunzatoare pentru PopupMenu [1 2 3 4]
%Prestabilit Ordin_f=1
%Conditionare de afisare in functie de valoarea butonului "Permanent"
%------------------------------------------------------------------------------
if Permanent==1
    uicontrol('Style','Text',...
              'Units','Normalized',...
              'Position',[0.05 -0.02 0.2 0.2],...
              'HorizontalAlignment','left',...
              'FontSize',10,...
              'String','f=',...
              'ForegroundColor',[1 0.2 0.2],...
              'Parent', RG1);
    uicontrol ('Style','Edit',...
               'Units','Normalized',...
               'Position',[0.15 0.095 0.39 0.105],...
               'HorizontalAlignment','right',...
               'FontSize',10,...
               'String', num2str(f),...
               'ForegroundColor',[1 0.2 0.2],...
               'Parent', RG1,...
               'Callback','f=str2num(get(gco,''string''))');
    uicontrol('Style','PopupMenu',...                
              'Units','normalized',...                
              'Position',[0.55 0 0.3 0.2],...
              'FontSize',10,...
              'String','Hz|kHz|MHz|GHz',...
              'Value',Ordin_f,...
              'ForegroundColor',[1 0.2 0.2],...
              'Parent', RG1,...
              'Callback','Ordin_f=get(gco,''value'')');
    switch Ordin_f
        case 2
            f=f*10^3;
        case 3
            f=f*10^6;
        case 4
            f=f*10^9;
    end
    %------------------------------------------------------------------------------
    %Container pentru gruparea elementelor de interfata
    %ce vor alcatui datele de iesire ale circuitului
    %Elemente de interfata( uicontrol ) incluse: Text
    %Delimitare sub forma tabelara cu ajutorul "axes" si "line"
    %------------------------------------------------------------------------------
    RG2=uibuttongroup('Visible','on',...
                      'ForegroundColor','black',...
                      'Title','Date calculate',...
                      'FontSize',11,...
                      'TitlePosition','centertop',...
                      'Tag','radiobutton',...
                      'HighlightColor',[0.6 0.6 1],...
                      'Position',[0.255 0.07 0.26 0.915]);
    %------------------------------------------------------------------------------               
end
switch Selectare_circuit
    %Selectare_circuit=1 => Circuit RLC Serie
    %------------------------------------------------------------------------------
    case 1
        if Permanent==1 && Plot==1
            %Analiza in regim permanent
            %Date ce vor fi calculate si afisate in containerul RG2 si
            %reprezentate pe axele folosite mai jos
            %------------------------------------------------------------------------------
            Plot=0;
            w=2*pi*f;
            T=1/f;
            t=0:T/50:N*T;
            v=A*sin(w*t); 
            Faza_z=atand((w*L-(1/(w*C)))/R);
            Faza_i=-Faza_z;
            modZ=sqrt(R.^2+(w*L-(1/(w*C))).^2);
            i=(A/modZ)*sin(w*t+Faza_i);
            vr=i.*R;
            vl=(A/modZ)*w*L*sin(w*t+Faza_i+90);
            vc=(A/modZ)*(1/(w*C))*sin(w*t+Faza_i-90);
            %------------------------------------------------------------------------------
            %Delimitare sub forma tabelara cu ajutorul "axes" si "line"
            %------------------------------------------------------------------------------
            a = axes;
            set(a, 'Visible', 'off');
            set(a, 'Position', [0, 0, 1, 1]);
            set(a,'Parent', RG2);
            set(a, 'Xlim', [0, 1], 'YLim', [0, 1]);
            line( [0.5 0.5],[0.2, 0.95], 'Parent', a, 'Color', [0.6 0.6 1])
            line( [0.25 0.25],[0.1, 0.2], 'Parent', a, 'Color', [0.6 0.6 1])
            line( [0.75 0.75],[0.1, 0.2], 'Parent', a, 'Color', [0.6 0.6 1])
            for y = 1 : 8
                line([0.05 0.95], [1 - y/10, 1-y/10], 'Parent', a,'Color',[0.6 0.6 1])
            end
            %------------------------------------------------------------------------------
            %Afisarea marimilor de interes ( Tensiune, Curent, Putere) si a
            %fazelor acestora prin fiecare element de circuit, precum si
            %frecventa de rezonanta
            %Nota: Valorile afisate reprezinta valorile de varf ale
            %marimilor de interes
            %------------------------------------------------------------------------------
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.9 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.6 0.6 1],...
                      'String',strcat('i=',ordin(A/modZ),'A'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.9 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.6 0.6 1],...
                      'String',strcat(char(hex2dec('03C6')),'i= ',num2str(Faza_i)),...
                      'Parent', RG2);     
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.8 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat('vR=',ordin((A/modZ)*R),'V'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.8 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat(char(hex2dec('03C6')),'R= ',num2str(Faza_i)),...
                      'Parent', RG2);     
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.7 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat('vL=',ordin((A/modZ)*w*L),'V'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.7 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat(char(hex2dec('03C6')),'L= ',num2str(Faza_i+90)),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.6 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat('vC= ',ordin((A/modZ)*(1/(w*C))),'V'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.6 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat(char(hex2dec('03C6')),'C= ',num2str(Faza_i-90)),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.5 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[1 0.2 0.2],...
                      'String',strcat('p= ',ordin(A*(A/modZ)),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.5 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[1 0.2 0.2],...
                      'String',strcat(char(hex2dec('03C6')),'p= ',num2str(2*Faza_i)),...
                      'Parent', RG2);        
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.4 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat('pR= ',ordin((A/modZ)^2*R),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.4 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat(char(hex2dec('03C6')),'R= ',num2str(2*Faza_i)),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.3 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat('VAXL= ',ordin((A/modZ)^2*w*L),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.3 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat(char(hex2dec('03C6')),'L= ',num2str(2*Faza_i+90)),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.2 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat('VAXC= ',ordin((A/modZ)^2*(1/(w*C))),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.2 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat(char(hex2dec('03C6')),'C= ',num2str(2*Faza_i-90)),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.3 0.1 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'String',strcat('f0= ',ordin(1/(2*pi*sqrt(L*C))),'Hz'),...
                      'Parent', RG2);
            %------------------------------------------------------------------------------
            %Realizarea axelor si afisarea semnalelor pentru fiecare
            %element de circuit
            %------------------------------------------------------------------------------
            y1 = axes('Units','Normalized','Position',[0.53 0.72 0.44 0.25],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            title('Tensiune','FontWeight','normal');      
            y2 = axes('Units','Normalized','Position',[0.53 0.72 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y3 = axes('Units','Normalized','Position',[0.53 0.72 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y4 = axes('Units','Normalized','Position',[0.53 0.72 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            plot(y1,t,v,'Color',[1 0.2 0.2]);
            plot(y2,t,vr,'Color',[0.8 0.4 0]);
            plot(y3,t,vl,'Color',[0.25 0.25 0.25]);
            plot(y4,t,vc,'Color',[0 0.6 0]);
            y1 = axes('Units','Normalized','Position',[0.53 0.39 0.44 0.25],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            plot(y1,t,i,'Color',[0.6 0.6 1]);
            title('Curent','FontWeight','normal');
            y1 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            title('Putere','FontWeight','normal');      
            y2 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y3 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y4 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            plot(y1,t,v.*i,'Color',[1 0.2 0.2]);      
            plot(y2,t,i.^2*R,'Color',[0.8 0.4 0]);
            plot(y3,t,((A/modZ)*sin(w*t+Faza_i+90)).^2*w*L,'Color',[0.25 0.25 0.25]);
            plot(y4,t,((A/modZ)*sin(w*t+Faza_i-90)).^2*(1/(w*C)),'Color',[0 0.6 0]);
            %------------------------------------------------------------------------------
        end
        if Tranzitoriu==1 && Plot==1
            %Analiza in regim tranzitoriu
            %------------------------------------------------------------------------------
            Plot=0;
            alpha=R/(2*L);
            [t,Vc]=ode45(@(t,Vc) Tensiune_Condensator(t,Vc,A,R,L,C),[0 6/alpha],[0;0]);
            y = axes('Units','Normalized','Position',[0.3 0.07 0.65 0.9],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            plot(y,t,Vc(:,2),'Color',[0 0.6 0]);
            title('Tensiune Condensator','FontWeight','normal');
            %------------------------------------------------------------------------------
        end
        if Permanent==1 || Tranzitoriu==1
            %Afisarea schemei electrice a circuitului
            %------------------------------------------------------------------------------
            img=imread('RLC Serie.jpg');
            subplot('Position',[0.025 0.07 0.19 0.26]);
            image(img);
            axis off; 
            %------------------------------------------------------------------------------
        end
    %------------------------------------------------------------------------------
    %Selectare_circuit=2 => Circuit RLC Paralel
    %------------------------------------------------------------------------------
    case 2
        if Permanent==1 && Plot==1
            %Analiza in regim permanent
            %Date ce vor fi calculate si afisate in containerul RG2 si
            %reprezentate pe axele folosite mai jos
            %------------------------------------------------------------------------------
            Plot=0;
            w=2*pi*f;
            T=1/f;
            t=0:T/50:N*T;
            v=A*sin(w*t); 
            Faza_z=atand(R)-atand(w*R*C-(R/(w*L)));
            Faza_i=-Faza_z;
            modZ=R/(sqrt(1+(w*R*C-(R/(w*L))).^2));
            i=(A/modZ)*sin(w*t+Faza_i);
            ir=v./R;
            il=(A/(w*L))*sin(w*t-90);
            ic=(A*w*C)*sin(w*t+90);
            %------------------------------------------------------------------------------
            %Delimitare sub forma tabelara cu ajutorul "axes" si "line"
            %------------------------------------------------------------------------------
            a = axes;
            set(a, 'Visible', 'off');
            set(a, 'Position', [0, 0, 1, 1]);
            set(a,'Parent', RG2);
            set(a, 'Xlim', [0, 1], 'YLim', [0, 1]);
            line( [0.5 0.5],[0.2, 0.95], 'Parent', a, 'Color', [0.6 0.6 1])
            line( [0.25 0.25],[0.1, 0.2], 'Parent', a, 'Color', [0.6 0.6 1])
            line( [0.75 0.75],[0.1, 0.2], 'Parent', a, 'Color', [0.6 0.6 1])
            for y = 1 : 8
                line([0.05 0.95], [1 - y/10, 1-y/10], 'Parent', a,'Color',[0.6 0.6 1])
            end
            %------------------------------------------------------------------------------
            %Afisarea marimilor de interes ( Tensiune, Curent, Putere) si a
            %fazelor acestora prin fiecare element de circuit, precum si
            %frecventa de rezonanta
            %Nota: Valorile afisate reprezinta valorile de varf ale
            %marimilor de interes
            %------------------------------------------------------------------------------
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.9 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.6 0.6 1],...
                      'String',strcat('I= ',ordin(A/modZ),'A'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.9 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.6 0.6 1],...
                      'String',strcat(char(hex2dec('03C6')),'v=',num2str(Faza_i)),...
                      'Parent', RG2);       
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.8 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat('Ir= ',ordin(A/R),'A'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.8 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat(char(hex2dec('03C6')),'R=0'),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.7 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat('Il= ',ordin(A/(w*L)),'A'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.7 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat(char(hex2dec('03C6')),'L=-90'),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.6 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat('Ic= ',ordin(A*w*C),'A'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.6 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat(char(hex2dec('03C6')),'C=90'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.5 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[1 0.2 0.2],...
                      'String',strcat('P= ',ordin(A*(A/modZ)),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.5 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[1 0.2 0.2],...
                      'String',strcat(char(hex2dec('03C6')),'p= ',num2str(2*Faza_i)),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.43 0.2 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat('Pr= ',ordin((A/R)^2*R),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.4 0.2 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.8 0.4 0],...
                      'String',strcat(char(hex2dec('03C6')),'R=0'),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.3 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat('VAXl= ',ordin((A/(w*L))^2*w*L),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.3 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0.25 0.25 0.25],...
                      'String',strcat(char(hex2dec('03C6')),'L=-90'),...
                      'Parent', RG2);      
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.05 0.2 0.43 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat('VAXc= ',ordin((A*w*C)^2*(1/(w*C))),'W'),...
                      'Parent', RG2);
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.55 0.2 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'ForegroundColor',[0 0.6 0],...
                      'String',strcat(char(hex2dec('03C6')),'C=90'),...
                      'Parent', RG2); 
            uicontrol('Style','Text',...
                      'Units','Normalized',...
                      'Position',[0.3 0.1 0.4 0.05],...
                      'HorizontalAlignment','left',...
                      'FontSize',10,...
                      'String',strcat('f0= ',ordin(1/(2*pi*sqrt(L*C))),'Hz'),...
                      'Parent', RG2);
            %------------------------------------------------------------------------------
            %Realizarea axelor si afisarea semnalelor pentru fiecare
            %element de circuit
            %------------------------------------------------------------------------------
            y1 = axes('Units','Normalized','Position',[0.53 0.72 0.44 0.25],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            title('Tensiune','FontWeight','normal');      
            plot(y1,t,v,'Color',[1 0.2 0.2]);
            y1 = axes('Units','Normalized','Position',[0.53 0.39 0.44 0.25],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            title('Curent','FontWeight','normal');      
            y2 = axes('Units','Normalized','Position',[0.53 0.39 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y3 = axes('Units','Normalized','Position',[0.53 0.39 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y4 = axes('Units','Normalized','Position',[0.53 0.39 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            plot(y1,t,i,'Color',[0.6 0.6 1]);
            plot(y2,t,ir,'Color',[0.8 0.4 0]);
            plot(y3,t,il,'Color',[0.25 0.25 0.25]);
            plot(y4,t,ic,'Color',[0 0.6 0]);
            y1 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            title('Putere','FontWeight','normal');      
            y2 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y3 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            y4 = axes('Units','Normalized','Position',[0.53 0.07 0.44 0.25],...
                      'Visible','off',...
                      'NextPlot','add');
            plot(y1,t,v.*i,'Color',[0.6 0.6 1]);      
            plot(y2,t,ir.^2*R,'Color',[0.8 0.4 0]);
            plot(y3,t,il.^2*w*L,'Color',[0.25 0.25 0.25]);
            plot(y4,t,ic.^2*(1/(w*C)),'Color',[0 0.6 0]);
            %------------------------------------------------------------------------------
        end
       if Tranzitoriu==1 && Plot==1
            %Analiza in regim tranzitoriu
            %------------------------------------------------------------------------------
            Plot=0;
            alpha=1/(2*R*C);
            [t,Il]=ode45(@(t,Il) Curent_Bobina(t,Il,A,R,L,C),[0 6/alpha],[0;0]);
            y = axes('Units','Normalized','Position',[0.3 0.07 0.65 0.9],...
                      'Color','w','XColor','k','YColor','none',...
                      'NextPlot','add');
            plot(y,t,Il(:,2),'Color',[0.25 0.25 0.25]);
            title('Curentul prin bobina');
            %------------------------------------------------------------------------------
        end
        if Permanent==1 || Tranzitoriu==1
            %Afisarea schemei electrice a circuitului
            %------------------------------------------------------------------------------
            img=imread('RLC Paralel.jpg');
            subplot('Position',[0.025 0.07 0.22 0.25]);
            image(img);
            axis off;
            %------------------------------------------------------------------------------
        end
    %end case 2
    %------------------------------------------------------------------------------
end
%end switch
%------------------------------------------------------------------------------
%Container pentru gruparea elementelor de interfata
%ce vor alcatui datele aditionale de intrare ale circuitului
%Elemente de interfata( uicontrol ) incluse: Text, Edit, PopupMenu,
%Pushbuton
%------------------------------------------------------------------------------
RG3=uibuttongroup('Visible','on',...
                  'ForegroundColor','black',...
                  'Title','Regim',...
                  'FontSize',11,...
                  'TitlePosition','centertop',...
                  'Tag','radiobutton',...
                  'HighlightColor',[0.6 0.6 1],...
                  'Position',[0.025 0.35 0.17 0.24]);
%------------------------------------------------------------------------------
%Elemente de interfata ce permit alegerea regimului in care se face analiza
%circuitului, selectarea circuitului si a numarului de perioade de
%vizualizare a semnalelor
%------------------------------------------------------------------------------
uicontrol('Style','pushbutton',...              
          'Units','normalized',...              
          'Position',[0.05 0.7 0.4 0.2],...
          'FontSize',10,...
          'String','Tranzitoriu',...
          'Value',Tranzitoriu,...
          'Parent', RG3,...
          'Callback','Tranzitoriu=get(gco,''value'');Permanent=0');
uicontrol('Style','pushbutton',...              
          'Units','normalized',...              
          'Position',[0.55 0.7 0.4 0.2],...
          'FontSize',10,...
          'String','Permanent',...
          'Value',Permanent,...
          'Parent', RG3,...
          'Callback','Permanent=get(gco,''value'');Tranzitoriu=0');     
if Permanent==1      
    uicontrol('Style','Text',...
              'Units','Normalized',...
              'Position',[0.07 0.36 0.5 0.2],...
              'FontSize',10,...
              'String','Nr. perioade=',...
              'Parent', RG3);
    uicontrol ('Style','Edit',...
              'Units','Normalized',...
              'Position',[0.55 0.4 0.3 0.2],...
              'FontSize',10,...
              'String', num2str(N), ...
              'Parent', RG3,...
              'Callback','N=str2num(get(gco,''string''))');
end
uicontrol ('Style','pushbutton',...
          'Units','Normalized',...
          'Position',[0.65 0.055 0.3 0.2],...
          'FontSize',10,...
          'String', 'Plot' , ...
          'Value',Plot,...
          'Parent',RG3,...
          'Callback','Plot=get(gco,''value'');close;figura(N,A,f,R,C,L,Ordin_R,Ordin_L,Ordin_C,Ordin_v,Ordin_f,Selectare_circuit,Permanent,Tranzitoriu,Plot)');        
uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.05 0.17 0.4 0.2],...
          'FontSize',10,...
          'String','Tip circuit:',...
          'Parent',RG3);
uicontrol('Style','PopupMenu',...                
          'Units','normalized',...                
          'Position',[0.05 0.05 0.55 0.2],...
          'FontSize',10,...
          'String','RLC Serie|RLC Paralel',...
          'Value',Selectare_circuit,...
          'Parent',RG3,...
          'Callback','Selectare_circuit=get(gco,''value'')');         
%------------------------------------------------------------------------------